@host = http://localhost:8081


####################
###Conductores
#################

GET {{host}}/drivers HTTP/1.1
###

GET {{host}}/drivers/1 HTTP/1.1
###

POST {{host}}/drivers HTTP/1.1
Content-Type: application/json

{
    "name": "jhonatan",
    "dni": "78947158",
    "license":"FBD-157",
    "birthdate": "1988-12-09"
}

###

PUT  {{host}}/drivers/8 HTTP/1.1
Content-Type: application/json

{
    "name": "Maria Lopez",
    "dni": "412345678",
    "license":"ABC-111",
    "birthdate": "1987-09-07"
}
###

DELETE {{host}}/drivers/7 HTTP/1.1
