@host = http://localhost:8081


####################
###Conductores
#################

GET {{host}}/drivers HTTP/1.1
###

GET {{host}}/drivers/10 HTTP/1.1
###

POST {{host}}/drivers HTTP/1.1
Content-Type: application/json

{
    "name": "jossimar neciosup",
    "dni": "4484718",
    "license":"FBD-158",
    "birthdate": "1988-12-09"
}

###

PUT {{host}}/drivers/9 HTTP/1.1
Content-Type: application/json

{
    "name": "jose mendoza",
    "dni": "78945611",
    "license":"DFE-951",
    "birthdate": "1987-12-07"
}
###

DELETE {{host}}/drivers/8 HTTP/1.1
